### ISSUE TITLE
Which version of node to use?

### ISSUE THREAD

**Issue by Redcraft7578** [kymotsujason/Paperback2Aidoku#1]
As the title says, its stuck at "Converting Library...". This is the error it gives me:
Unhandled Runtime Error

TypeError: mangaInfo.tags[0] is undefined
Source

src\app\paperback2aidoku.jsx (118:25) @ mangaInfo

  116 | 			const status = convertMangaStatus(statusText);
  117 | 			const tags = [];
> 118 | 			for (let tagIndex in mangaInfo.tags[0].tags) {
      | 			                     ^
  119 | 				tags.push(mangaInfo.tags[0].tags[tagIndex].label);
  120 | 			}
  121 | 			sourceCount[sourceId] = (sourceCount[sourceId] || 0) + 1;

**Comment by kymotsujason** [comment]
The node version I used is v21.7.0, but that shouldn't be the issue here. It looks like one of your mangas doesn't have a tag property and there was no check for that. I've added a check, but there's a chance something else will break. Try it again and let me know. If it works, make sure the manga count it outputs matches what you expect.
